### ISSUE TITLE
My project cannot find cmake files

### ISSUE THREAD

**Issue by charlest001** [oatpp/oatpp-mbedtls#7]
After building with the instructions, cmake in my project does not find the correct files for for compilation.

This is the error I recieve:

CMake Error at CMakeLists.txt:25 (find_package):
  By not providing "Findoatpp-mbedtls.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "oatpp-mbedtls", but CMake did not find one.

  Could not find a package configuration file provided by "oatpp-mbedtls"
  (requested version 1.0.0) with any of the following names:

    oatpp-mbedtlsConfig.cmake
    oatpp-mbedtls-config.cmake

  Add the installation prefix of "oatpp-mbedtls" to CMAKE_PREFIX_PATH or set
  "oatpp-mbedtls_DIR" to a directory containing one of the above files.  If
  "oatpp-mbedtls" provides a separate development package or SDK, be sure it
  has been installed.

I checked in my installation directory to see that the install created the above mentioned .cmake files
but could not find them.

Thanks

**Comment by lganzzzo** [comment]
Hello @charlest001 ,

Please provide more details:
- What operating system do you use? Is it Windows?
- Are you installing oatpp-mbedtls to a custom location?

Regards,
Leonid

**Comment by charlest001** [comment]
I am using Ubuntu 18.04.4 LTS.

I did not install to a custom location.

**Comment by lganzzzo** [comment]
Hey @charlest001 ,

Please run `make install` and make sure that all the files were actually installed.
make will write the list of all the files installed with the full paths.

```bash
$ make install

...

Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/oatpp-1.0.0/liboatpp-mbedtls.a
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/Connection.hpp
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/Config.hpp
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/server
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/server/ConnectionProvider.hpp
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/client
-- Up-to-date: /usr/local/include/oatpp-1.0.0/oatpp-mbedtls/oatpp-mbedtls/client/ConnectionProvider.hpp
-- Installing: /usr/local/lib/cmake/oatpp-mbedtls-1.0.0/oatpp-mbedtlsTargets.cmake
-- Installing: /usr/local/lib/cmake/oatpp-mbedtls-1.0.0/oatpp-mbedtlsTargets-noconfig.cmake
-- Installing: /usr/local/lib/cmake/oatpp-mbedtls-1.0.0/oatpp-mbedtlsConfig.cmake
-- Installing: /usr/local/lib/cmake/oatpp-mbedtls-1.0.0/oatpp-mbedtlsConfigVersion.cmake
```

make sure that you didn't get the permission-denied errors.

Regards,
Leonid

**Comment by charlest001** [comment]
I ran this and still has the same problem.. 

This is the output:

Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libmbedtls.a
-- Installing: /usr/local/lib/libmbedx509.a
-- Installing: /usr/local/lib/libmbedcrypto.a
-- Installing: /usr/local/include/mbedtls/aes.h
-- Installing: /usr/local/include/mbedtls/aesni.h
-- Installing: /usr/local/include/mbedtls/arc4.h
-- Installing: /usr/local/include/mbedtls/aria.h
-- Installing: /usr/local/include/mbedtls/asn1.h
-- Installing: /usr/local/include/mbedtls/asn1write.h
-- Installing: /usr/local/include/mbedtls/base64.h
-- Installing: /usr/local/include/mbedtls/bignum.h
-- Installing: /usr/local/include/mbedtls/blowfish.h
-- Installing: /usr/local/include/mbedtls/bn_mul.h
-- Installing: /usr/local/include/mbedtls/camellia.h
-- Installing: /usr/local/include/mbedtls/ccm.h
-- Installing: /usr/local/include/mbedtls/certs.h
-- Installing: /usr/local/include/mbedtls/chacha20.h
-- Installing: /usr/local/include/mbedtls/chachapoly.h
-- Installing: /usr/local/include/mbedtls/check_config.h
-- Installing: /usr/local/include/mbedtls/cipher.h
-- Installing: /usr/local/include/mbedtls/cipher_internal.h
-- Installing: /usr/local/include/mbedtls/cmac.h
-- Installing: /usr/local/include/mbedtls/compat-1.3.h
-- Installing: /usr/local/include/mbedtls/config.h
-- Installing: /usr/local/include/mbedtls/ctr_drbg.h
-- Installing: /usr/local/include/mbedtls/debug.h
-- Installing: /usr/local/include/mbedtls/des.h
-- Installing: /usr/local/include/mbedtls/dhm.h
-- Installing: /usr/local/include/mbedtls/ecdh.h
-- Installing: /usr/local/include/mbedtls/ecdsa.h
-- Installing: /usr/local/include/mbedtls/ecjpake.h
-- Installing: /usr/local/include/mbedtls/ecp.h
-- Installing: /usr/local/include/mbedtls/ecp_internal.h
-- Installing: /usr/local/include/mbedtls/entropy.h
-- Installing: /usr/local/include/mbedtls/entropy_poll.h
-- Installing: /usr/local/include/mbedtls/error.h
-- Installing: /usr/local/include/mbedtls/gcm.h
-- Installing: /usr/local/include/mbedtls/havege.h
-- Installing: /usr/local/include/mbedtls/hkdf.h
-- Installing: /usr/local/include/mbedtls/hmac_drbg.h
-- Installing: /usr/local/include/mbedtls/md.h
-- Installing: /usr/local/include/mbedtls/md2.h
-- Installing: /usr/local/include/mbedtls/md4.h
-- Installing: /usr/local/include/mbedtls/md5.h
-- Installing: /usr/local/include/mbedtls/md_internal.h
-- Installing: /usr/local/include/mbedtls/memory_buffer_alloc.h
-- Installing: /usr/local/include/mbedtls/net.h
-- Installing: /usr/local/include/mbedtls/net_sockets.h
-- Installing: /usr/local/include/mbedtls/nist_kw.h
-- Installing: /usr/local/include/mbedtls/oid.h
-- Installing: /usr/local/include/mbedtls/padlock.h
-- Installing: /usr/local/include/mbedtls/pem.h
-- Installing: /usr/local/include/mbedtls/pk.h
-- Installing: /usr/local/include/mbedtls/pk_internal.h
-- Installing: /usr/local/include/mbedtls/pkcs11.h
-- Installing: /usr/local/include/mbedtls/pkcs12.h
-- Installing: /usr/local/include/mbedtls/pkcs5.h
-- Installing: /usr/local/include/mbedtls/platform.h
-- Installing: /usr/local/include/mbedtls/platform_time.h
-- Installing: /usr/local/include/mbedtls/platform_util.h
-- Installing: /usr/local/include/mbedtls/poly1305.h
-- Installing: /usr/local/include/mbedtls/ripemd160.h
-- Installing: /usr/local/include/mbedtls/rsa.h
-- Installing: /usr/local/include/mbedtls/rsa_internal.h
-- Installing: /usr/local/include/mbedtls/sha1.h
-- Installing: /usr/local/include/mbedtls/sha256.h
-- Installing: /usr/local/include/mbedtls/sha512.h
-- Installing: /usr/local/include/mbedtls/ssl.h
-- Installing: /usr/local/include/mbedtls/ssl_cache.h
-- Installing: /usr/local/include/mbedtls/ssl_ciphersuites.h
-- Installing: /usr/local/include/mbedtls/ssl_cookie.h
-- Installing: /usr/local/include/mbedtls/ssl_internal.h
-- Installing: /usr/local/include/mbedtls/ssl_ticket.h
-- Installing: /usr/local/include/mbedtls/threading.h
-- Installing: /usr/local/include/mbedtls/timing.h
-- Installing: /usr/local/include/mbedtls/version.h
-- Installing: /usr/local/include/mbedtls/x509.h
-- Installing: /usr/local/include/mbedtls/x509_crl.h
-- Installing: /usr/local/include/mbedtls/x509_crt.h
-- Installing: /usr/local/include/mbedtls/x509_csr.h
-- Installing: /usr/local/include/mbedtls/xtea.h
-- Up-to-date: /usr/local/bin/aescrypt2
-- Up-to-date: /usr/local/bin/crypt_and_hash
-- Up-to-date: /usr/local/bin/hello
-- Up-to-date: /usr/local/bin/generic_sum
-- Up-to-date: /usr/local/bin/dh_client
-- Up-to-date: /usr/local/bin/dh_genprime
-- Up-to-date: /usr/local/bin/dh_server
-- Up-to-date: /usr/local/bin/key_app
-- Up-to-date: /usr/local/bin/mpi_demo
-- Up-to-date: /usr/local/bin/rsa_genkey
-- Up-to-date: /usr/local/bin/rsa_sign
-- Up-to-date: /usr/local/bin/rsa_verify
-- Up-to-date: /usr/local/bin/rsa_encrypt
-- Up-to-date: /usr/local/bin/rsa_decrypt
-- Up-to-date: /usr/local/bin/pk_encrypt
-- Up-to-date: /usr/local/bin/pk_decrypt
-- Up-to-date: /usr/local/bin/pk_sign
-- Up-to-date: /usr/local/bin/pk_verify
-- Up-to-date: /usr/local/bin/gen_key
-- Up-to-date: /usr/local/bin/gen_random_havege
-- Up-to-date: /usr/local/bin/gen_random_ctr_drbg
-- Up-to-date: /usr/local/bin/gen_entropy
-- Up-to-date: /usr/local/bin/dtls_client
-- Up-to-date: /usr/local/bin/dtls_server
-- Up-to-date: /usr/local/bin/ssl_client1
-- Up-to-date: /usr/local/bin/ssl_client2
-- Up-to-date: /usr/local/bin/ssl_server
-- Up-to-date: /usr/local/bin/ssl_fork_server
-- Up-to-date: /usr/local/bin/ssl_mail_client
-- Up-to-date: /usr/local/bin/mini_client
-- Up-to-date: /usr/local/bin/ssl_pthread_server
-- Up-to-date: /usr/local/bin/selftest
-- Up-to-date: /usr/local/bin/benchmark
-- Up-to-date: /usr/local/bin/ssl_cert_test
-- Up-to-date: /usr/local/bin/udp_proxy
-- Up-to-date: /usr/local/bin/query_compile_time_config
-- Up-to-date: /usr/local/bin/cert_app
-- Up-to-date: /usr/local/bin/crl_app
-- Up-to-date: /usr/local/bin/req_app
-- Up-to-date: /usr/local/bin/cert_req
-- Up-to-date: /usr/local/bin/cert_write
-- Up-to-date: /usr/local/bin/strerror
-- Up-to-date: /usr/local/bin/pem2der

**Comment by lganzzzo** [comment]
Hey @charlest001 ,
Your log is for `MbedTLS`, not for `oatpp-mbedtls`.

- `MbedTLS` - is the actual TLS library
- `oatpp-mbedtls` - is the adaptor for `MbedTLS` to work with `oatpp`

You have to install:
- oatpp - main oatpp module
- MbedTLS - TLS lib
- oatpp-mbedtls - tls adaptor for oatpp

Then you can run your application.

Regards,
Leonid

**Comment by charlest001** [comment]
Thanks!
All working well!

**Comment by lganzzzo** [comment]
Hey, 

Thanks for letting us know!
Closing issue...

Regards,
Leonid
